services:

  task-manager:
    build: .
    image: task-manager:0.2
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      - redis

  redis-populate:
    image: redis
    entrypoint: [ "/redis-populate.sh", "/redis-populate.txt" ]
    depends_on:
      - redis
    env_file:
      - ./.env.redis-populate
    volumes:
      - ./redis-populate.txt:/redis-populate.txt
      - ./redis-populate.sh:/redis-populate.sh

  redis:
    image: redis
    ports:
      - 6379:6379
