services:

  task-manager:
    build: .
    image: task-manager:0.2
    networks:
      - task-manager-public-network
      - redis-network
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/ping" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      - redis

  redis:
    image: redis
    networks:
      - redis-network
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  redis-backup:
    image: bash
    networks:
      - task-manager-public-network
    entrypoint: [ "/snapshot-backup.sh" ]
    depends_on:
      - redis
    environment:
      - BACKUP_PERIOD=10
    volumes:
      - ./snapshot-backup.sh:/snapshot-backup.sh
      - redis-data:/data:ro
      - backup:/backup

networks:
  task-manager-public-network:
    labels:
      - com.packtpub.compose.app=task-manager

  redis-network:
    labels:
      - com.packtpub.compose.app=task-manager

volumes:
  redis-data:
    labels:
      - com.packtpub.compose.app=task-manager
  backup:
