services:

  task-manager:
    build:
      context: task-manager
    image: task-manager:0.1
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
      - LOCATION_HOST=http://location-service:8080
    depends_on:
      - redis
      - location-service
    networks:
      - location-network
      - redis-network
      - monitoring-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://location:8080/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
