services:
  prometheus:
    image: prom/prometheus
    ports: 
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yaml
    networks:
      - monitoring-network
    depends_on:
      - task-manager
  push-gateway:
    image: prom/pushgateway
    networks:
      - monitoring-network